import { Guest } from '@/types/guest'

/**
 * Table numbers are set explicitly (not via the bin-packing helper) so the
 * demo shows all three table states out of the box: Bàn 1 full (10/10),
 * Bàn 2 overloaded (12/10), Bàn 3 with room (2/10).
 */
export const sampleGuests: Guest[] = [
  {
    id: 'sample-1',
    name: 'Nguyễn Văn Hùng',
    phone: '0901234567',
    side: 'Nhà trai',
    group: 'Họ hàng',
    partySize: 4,
    status: 'Sẽ đến',
    table: 1,
    note: 'Bác ruột chú rể',
  },
  {
    id: 'sample-2',
    name: 'Trần Thị Lan',
    phone: '0912345678',
    side: 'Nhà gái',
    group: 'Họ hàng',
    partySize: 3,
    status: 'Sẽ đến',
    table: 1,
    note: '',
  },
  {
    id: 'sample-3',
    name: 'Lê Minh Tuấn',
    phone: '0923456789',
    side: 'Nhà trai',
    group: 'Bạn bè',
    partySize: 3,
    status: 'Sẽ đến',
    table: 1,
    note: 'Bạn đại học',
  },
  {
    id: 'sample-4',
    name: 'Phạm Thu Hà',
    phone: '0934567890',
    side: 'Nhà gái',
    group: 'Đồng nghiệp',
    partySize: 5,
    status: 'Sẽ đến',
    table: 2,
    note: '',
  },
  {
    id: 'sample-5',
    name: 'Hoàng Đức Anh',
    phone: '0945678901',
    side: 'Nhà trai',
    group: 'Đối tác',
    partySize: 4,
    status: 'Sẽ đến',
    table: 2,
    note: '',
  },
  {
    id: 'sample-6',
    name: 'Vũ Thị Mai',
    phone: '0956789012',
    side: 'Nhà gái',
    group: 'Bạn bè',
    partySize: 3,
    status: 'Sẽ đến',
    table: 2,
    note: 'Nhóm bạn thân — bàn 2 đang quá tải, cần chuyển bớt',
  },
  {
    id: 'sample-7',
    name: 'Đặng Quốc Bảo',
    phone: '0967890123',
    side: 'Nhà trai',
    group: 'Hàng xóm',
    partySize: 2,
    status: 'Sẽ đến',
    table: 3,
    note: '',
  },
  {
    id: 'sample-8',
    name: 'Ngô Thị Thu',
    phone: '0978901234',
    side: 'Nhà gái',
    group: 'Khác',
    partySize: 1,
    status: 'Đã mời',
    table: null,
    note: '',
  },
  {
    id: 'sample-9',
    name: 'Bùi Văn Long',
    phone: '0989012345',
    side: 'Nhà trai',
    group: 'Bạn bè',
    partySize: 2,
    status: 'Chưa mời',
    table: null,
    note: '',
  },
  {
    id: 'sample-10',
    name: 'Đỗ Thị Hoa',
    phone: '0990123456',
    side: 'Nhà gái',
    group: 'Họ hàng',
    partySize: 1,
    status: 'Không đến',
    table: null,
    note: 'Bận việc gia đình',
  },
]
